services:
  frontend-service:
    build:
      context: ./frontend-service
    container_name: frontend-service
    ports:
      - 3000:3000
    depends_on:
      - question-service
      - users-service
    environment:
      REACT_APP_QUESTIONS_SERVICE_HOST: http://localhost:3001
      REACT_APP_USERS_SERVICE_HOST: http://localhost:3002
    volumes:
      - ./frontend-service:/app
    command: yarn start

  question-service:
    build:
      context: ./question-service
    container_name: question-service
    ports:
      - 3001:3001
    depends_on:
      - mongodb
    environment:
      PORT: 3001
      USERS_SERVICE_HOST: http://users-service:3002
    volumes:
      - ./question-service:/app
    command: yarn start

  users-service:
    build:
      context: ./users-service
    container_name: users-service
    ports:
      - 3002:3002
    depends_on:
      - postgresql
    environment:
      PORT: 3002
      DB_HOST: postgresql
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    volumes:
      - ./users-service:/app
    command: yarn start
  
  matchmaking-service:
    build:
      context: ./matchmaking-service
    container_name: matchmaking-service
    ports:
      - 3003:3003
    depends_on:
      - users-service
      - rabbitmq
    environment:
      PORT: 3003
      USERS_SERVICE_HOST: http://users-service:3002
    volumes:
      - ./matchmaking-service:/app
    command: yarn start

  postgresql:
    image: postgres:15-alpine
    container_name: postgresql
    volumes:
      - "postgres:/var/lib/postgresql/data"
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  mongodb:
    image: mongo:7.0.1
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: testpw
      MONGO_INITDB_DATABASE: peerprep-database

  mongo-ui:
    image: mongo-express
    container_name: mongo-ui
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: testpw
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://test:testpw@mongodb:27017/

  pgadmin:
    image: dpage/pgadmin4
    container_name: pg-admin
    restart: always
    ports:
      - 8082:80
    depends_on:
      - postgresql
    environment:
      PGADMIN_DEFAULT_EMAIL: test@gmail.com
      PGADMIN_DEFAULT_PASSWORD: test
      PGADMIN_LISTEN_PORT: 80

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  postgres:
