services:
  frontend-service:
    build:
      context: ./frontend-service
    container_name: frontend-service
    ports:
      - 3000:3000
    depends_on:
      - question-service
      - users-service
    environment:
      REACT_APP_QUESTIONS_SERVICE_HOST: http://localhost:3001
    volumes:
      - ./frontend-service:/app
    command: yarn start

  question-service:
    build:
      context: ./question-service
    container_name: question-service
    ports:
      - 3001:3001
    depends_on:
      - mongodb
    environment:
      PORT: 3001
      MONGO_LOCAL_URI: mongodb://test:testpw@localhost:27017/?retryWrites=true&w=majority&maxPoolSize=20
      MONGO_LOCAL_DOCKER_URI: mongodb://test:testpw@mongodb:27017/?retryWrites=true&w=majority&maxPoolSize=20
    volumes:
      - ./question-service:/app
    command: yarn start

  mongodb:
    image: mongo:7.0.1
    container_name: mongodb
    restart: always
    volumes:
      - "mongodb-data:/data/db"
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: testpw
      MONGO_INITDB_DATABASE: peerprep-database

volumes:
  mongodb-data:
