services:
  mongo-ui:
    image: mongo-express
    container_name: mongo-ui
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: testpw
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://test:testpw@mongodb:27017/

  pgadmin:
    image: dpage/pgadmin4
    container_name: pg-admin
    restart: always
    ports:
      - 8082:80
    depends_on:
      - postgresql
    environment:
      PGADMIN_DEFAULT_EMAIL: test@gmail.com
      PGADMIN_DEFAULT_PASSWORD: test
      PGADMIN_LISTEN_PORT: 80
