services:
  mongo-ui:
    image: mongo-express
    container_name: mongo-ui
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_BASICAUTH_USERNAME:
      ME_CONFIG_BASICAUTH_PASSWORD: 
      ME_CONFIG_MONGODB_URL: mongodb://test:testpw@mongodb:27017/
