services:
  users:
    build:
      context: ./users
    container_name: users
    ports:
      - 3002:3002
    depends_on:
      - postgresql
    environment:
      PORT: 3002
      DB_HOST: postgresql
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    command: node index.js

  postgresql:
    image: postgres:15-alpine
    container_name: postgresql
    volumes:
      - "postgres:/var/lib/postgresql/data"
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres:
