name: Build and Deploy Frontend to Production Branch

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code (master)
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./frontend-service

      - name: Build frontend (master)
        run: |
          export REACT_APP_QUESTIONS_SERVICE_HOST=http://peerprep.bryanlohxz.com/api/questions-service
          export REACT_APP_USERS_SERVICE_HOST=http://peerprep.bryanlohxz.com/api/users-service
          export REACT_APP_MATCHMAKING_SERVICE_HOST=http://peerprep.bryanlohxz.com/api/matchmaking-service
          export CI=false
          yarn build
        working-directory: ./frontend-service

      - name: Checkout code (production)
        uses: actions/checkout@v4
        with:
          ref: production-actions-test

      - name: Update build in production
        run: |
          rm -rf build
          git checkout master -- ./build
          git add ./build
          git commit -m "Update build"
        working-directory: ./frontend-service
