name: Run tests on PeerPrepTest

on:
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Install dependencies
        run: yarn install --frozen-lockfile --production=false

      - name: Run all tests
        run: yarn test
